apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "brew-app.fullname" . }}
  labels:
{{ include "brew-app.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "brew-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "brew-app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health-check
              port: http
          readinessProbe:
            httpGet:
              path: /health-check
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: AUTH0_DOMAIN
              value: {{ .Values.auth0Domain | quote }}
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "brew-app.name" . }}-secret
                  key: auth0-client-id
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "brew-app.name" . }}-secret
                  key: auth0-client-secret
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "brew-app.name" . }}-secret
                  key: jwt-secret
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "brew-app.name" . }}-secret
                  key: session-secret
            - name: AUTH0_CALLBACK_URL
              value: {{ .Values.auth0CallbackURL | quote }}
            - name: BREW_API_HOST
              value: {{ .Values.brewApiHost | quote }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
