apiVersion: v1
kind: Secret
metadata:
  name: {{ include "brew-app.name" . }}-secret
  labels:
{{ include "brew-app.labels" . | indent 4 }}
type: Opaque
data:
  auth0-client-id: {{ .Values.auth0ClientId | b64enc | quote }}
  auth0-client-secret: {{ .Values.auth0ClientSecret | b64enc | quote }}
  jwt-secret: {{ .Values.jwtSecret | b64enc | quote }}
  {{ if .Values.sessionSecret }}
  session-secret: {{ .Values.sessionSecret | b64enc | quote }}
  {{ else }}
  session-secret: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}
