image: node:10

cache:
  paths:
    - node_modules/

stages:
  - test
  - staging

test:
  stage: test
  script:
    - npm install
    - npm test

staging:
  type: deploy
  stage: staging
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=geekspace-brew-app-staging --api-key=$(echo $HEROKU_API_KEY | base64 --decode)
  only:
    - dev
